"""flat2

Revision ID: 577a8dcea9aa
Revises: 6e8a2a0e7a74
Create Date: 2023-08-07 14:32:46.207990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577a8dcea9aa'
down_revision = '6e8a2a0e7a74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
